### ISSUE TITLE
use robots.txt-style 'Name: value' formatting

### ISSUE THREAD

**Issue by jmason** [thegreenwebfoundation/carbon.txt#6]
I think this is a fantastic approach and well worth doing.  One thing that would improve it IMO would be to use a "Header: value" style more similar to robots.txt, though;

So for instance, instead of

```
[upstream]
krystal.co.uk
```

it'd use something like

```
[upstream]
Domain: krystal.co.uk
```

Or other kinds of identifier:

```
[upstream]
Name: Ecotricity Group Ltd
```

This gives more room for extensibility in future, where new forms of addressing or relationships can be supported.

**Comment by derhuerst** [comment]
I propose to use format like [TOML](https://toml.io/), as it is both highly human-readable and can be parsed in a strict manner.

**Comment by mrchrisadams** [comment]
We ended up using TOML in the end, so I'm closing this for now.
