### ISSUE TITLE
Define how to include comments

### ISSUE THREAD

**Issue by jmason** [thegreenwebfoundation/carbon.txt#7]
I might have missed it, but there doesn't seem to be any mention of how to include human-readable comments in the carbon.txt format.  Ignoring anything from a "#" char to the end of line would be fairly standard, and is what robots.txt uses.

**Comment by mrchrisadams** [comment]
I'm closing this, we now have settled on using [TOML](https://toml.io/en/), which has unambigous syntax for comments.
